import Head from "next/head";
import Image from "next/image";
import frontCard from "../public/images/bg-card-front.png";
import backCard from "../public/images/bg-card-back.png";
import cardIcon from "../public/images/card-logo.svg";
import completeIcon from "../public/images/icon-complete.svg";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import { validateForm } from "@/utils/validateFrom";

export default function Home() {
	const [formData, setFormData] = useState({
		cardholderName: "",
		cardNumber: "",
		month: "",
		year: "",
		cvc: "",
	});

	const [errors, setErrors] = useState({});
	const [formSubmitted, isFormSubmitted] = useState(false);

	const formatCardNumber = (input) => {
		const chunks = input.match(/.{1,4}/g) || [];
		const formattedInput = chunks.join(" ");
		return formattedInput;
	};

	const handleMonthYearChange = (event) => {
		const { name, value } = event.target;
		let sanitizedValue;
		name === "month" || name === "year"
			? (sanitizedValue = value.replace(/[^0-9]/g, "").slice(0, 2))
			: (sanitizedValue = value.replace(/[^0-9]/g, "").slice(0, 3));
		setFormData((prevData) => ({
			...prevData,
			[name]: value === "" ? "" : sanitizedValue,
		}));
	};

	const handleChange = (event) => {
		const { name, value } = event.target;
		setFormData((prevData) => ({
			...prevData,
			[name]: value,
		}));
	};

	const handleSubmit = (e) => {
		e.preventDefault();
		const errors = validateForm(formData);
		setErrors(errors);
		if (Object.keys(errors).length === 0) {
			console.log(formData);
			isFormSubmitted(true);
		}
	};

	const handleReset = (e) => {
		isFormSubmitted(false);
		setFormData({
			cardholderName: "",
			cardNumber: "",
			month: "",
			year: "",
			cvc: "",
		});
	};
	return (
		<>
			<Head>
				<title>Interactive Card Challenge</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<section className={styles.sideContainer}>
					<div className={styles.cardContainerWrapper}>
						<div className={styles.cardContainer}>
							<div className={styles.frontCardContainer}>
								<Image
									src={frontCard}
									alt="Front of the card with card details"
									width={350}
									className={styles.cardDesktop}
								/>
								<Image
									src={frontCard}
									alt="Front of the card with card details"
									width={280}
									className={styles.mobileCard}
								/>
								<div className={styles.frontCardInfo}>
									<Image
										className={styles.cardIcon}
										src={cardIcon}
										alt="Card Icon"
										width={75}
									/>
									<div className={styles.cardTextContainer}>
										<p className={styles.cardText}>
											{formData.cardNumber
												? formatCardNumber(formData.cardNumber)
												: "0000 0000 0000 0000"}
										</p>
										<div className={styles.cardNameandDate}>
											<p className={styles.cardText}>
												{formData.cardholderName
													? formData.cardholderName
													: "Jane Appleseed"}
											</p>
											<p className={styles.cardText}>
												{formData.month ? formData.month : "MM"} /
												{formData.year ? formData.year : "YY"}
											</p>
										</div>
									</div>
								</div>
							</div>
							<div className={styles.backCardContainer}>
								<Image
									src={backCard}
									alt="Back of the card with cvc number"
									width={350}
									className={styles.cardDesktop}
								/>
								<Image
									src={backCard}
									alt="Back of the card with cvc number"
									width={280}
									className={styles.mobileCard}
								/>
								<div className={styles.cvcContainer}>
									<p>{formData.cvc ? formData.cvc : "000"}</p>
								</div>
							</div>
						</div>
					</div>
				</section>
				{!formSubmitted ? (
					<section className={styles.formContainer}>
						<form className={styles.formWrapper} onSubmit={handleSubmit}>
							<div className={styles.formArea}>
								<div className={styles.formSection}>
									<label htmlFor="cardholderName" className={styles.labelStyle}>
										{"Cardholder Name".toUpperCase()}
									</label>
									<input
										name="cardholderName"
										placeholder="e.g. Jane Appleseed"
										onChange={handleChange}
										value={formData.cardholderName}
										className={`${styles.inputStyle} ${
											errors.name && styles.errorBox
										}`}
									/>
									<span className={styles.errorMsgs}>{errors.name}</span>
								</div>
								<div className={styles.formSection}>
									<label htmlFor="cardNumber" className={styles.labelStyle}>
										CARD NUMBER
									</label>
									<input
										name="cardNumber"
										placeholder="e.g. 1234 5678 9123 0000"
										onChange={handleChange}
										value={formData.cardNumber}
										maxLength={16}
										className={`${styles.inputStyle} ${
											errors.cardNumber && styles.errorBox
										}`}
									/>
									<span className={styles.errorMsgs}>{errors.cardNumber}</span>
								</div>
								<div
									className={`${styles.formSection} ${styles.formThirdSection}`}
								>
									<div className={styles.dateContainer}>
										<label htmlFor="exp-date" className={styles.labelStyle}>
											EXP DATE (MM/YY)
										</label>
										<div className={styles.dateWrapper}>
											<input
												name="month"
												type="text"
												pattern="\d*"
												maxLength="2"
												placeholder="MM"
												onChange={handleMonthYearChange}
												value={formData.month}
												className={`${styles.inputStyle} ${
													errors.month && styles.errorBox
												}`}
											/>
											<input
												name="year"
												type="text"
												pattern="\d*"
												maxLength="2"
												placeholder="YY"
												onChange={handleMonthYearChange}
												value={formData.year}
												className={`${styles.inputStyle} ${
													errors.year && styles.errorBox
												}`}
											/>
										</div>
										{errors.year && errors.month && (
											<span className={styles.errorMsgs}>{errors.year}</span>
										)}
									</div>
									<div className={styles.cvcInputContainer}>
										<label htmlFor="cvc" className={styles.labelStyle}>
											CVC
										</label>
										<input
											name="cvc"
											placeholder="e.g. 123"
											onChange={handleMonthYearChange}
											value={formData.cvc}
											maxLength="3"
											className={`${styles.inputStyle} ${
												errors.cvc && styles.errorBox
											}`}
										/>
										<span className={styles.errorMsgs}>{errors.cvc}</span>
									</div>
								</div>
								<div className={styles.formButton}>
									<button type="submit">Confirm</button>
								</div>
							</div>
						</form>
					</section>
				) : (
					<section className={styles.confirmationWrapper}>
						<Image
							src={completeIcon}
							alt="Icon showing that the process has completed"
						/>
						<p>THANK YOU!</p>
						<p>We&apos;ve added your card details</p>
						<div className={styles.formButton}>
							<button onClick={handleReset}>Continue</button>
						</div>
					</section>
				)}
				{/* Here is the Form Section */}
			</main>
		</>
	);
}
